"""Frozen schema revision; do not import live ORM models here."""
from alembic import op
import sqlalchemy as sa

revision = '0001_review'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('source_row_id', sa.Integer(), nullable=False),
    sa.Column('feature_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_source_row_id'), 'cases', ['source_row_id'], unique=True)
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('experiment', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('dataset_sha256', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_sha256', sa.String(length=64), nullable=False),
    sa.Column('scored_month', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('population_cases', sa.Integer(), nullable=False),
    sa.Column('selected_cases', sa.Integer(), nullable=False),
    sa.Column('summary_sha256', sa.String(length=64), nullable=False),
    sa.Column('queue_sha256', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('queue_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_rank', sa.Integer(), nullable=False),
    sa.Column('risk_percentile', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('analyst_note', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_id', name='uq_queue_run_case'),
    sa.UniqueConstraint('run_id', 'risk_rank', name='uq_queue_run_rank')
    )
    op.create_index(op.f('ix_queue_entries_case_id'), 'queue_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_queue_entries_decision'), 'queue_entries', ['decision'], unique=False)
    op.create_index(op.f('ix_queue_entries_review_status'), 'queue_entries', ['review_status'], unique=False)
    op.create_index(op.f('ix_queue_entries_run_id'), 'queue_entries', ['run_id'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_entry_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('analyst_note', sa.Text(), nullable=False),
    sa.Column('analyst_id', sa.String(length=128), nullable=True),
    sa.Column('case_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_queue_entry_id'), 'review_events', ['queue_entry_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrades disabled; restore a verified backup instead")
