"""Frozen schema revision; do not import live ORM models here."""
from alembic import op
import sqlalchemy as sa

revision = '0002_auth'
down_revision = '0001_review'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credentials',
    sa.Column('credential_id', sa.String(length=32), nullable=False),
    sa.Column('analyst_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'analyst', 'admin')", name='ck_credential_role'),
    sa.PrimaryKeyConstraint('credential_id'),
    sa.UniqueConstraint('token_sha256')
    )
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrades disabled; restore a verified backup instead")
