"""Persist versioned case explanations without modifying cases or reviews."""
from alembic import op
import sqlalchemy as sa

revision = "0003_explanations"
down_revision = "0002_auth"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_entry_id', sa.Integer(), nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=False),
    sa.Column('model_sha256', sa.String(length=64), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('background_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_entry_id', 'config_sha256', name='uq_explanation_entry_config')
    )
    op.create_index(op.f('ix_case_explanations_queue_entry_id'), 'case_explanations', ['queue_entry_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrades disabled; restore a verified backup instead")
